# Generated by Django 6.0.5 on 2026-06-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/'),
        ),
    ]
